### ISSUE TITLE
Playback 0.3.4 cannot work with pip 8.1.1

### ISSUE THREAD

**Issue by jiasir** [jiasir/playback#20]
Using pip 8.1.1 to install Playback failed:
```
'Requirement' object has no attribute 'project_name'
```

**Comment by jiasir** [comment]
1, If you installed pip from apt, remove python-pip(8.1.1): `sudo apt remove --purge python-pip`
2, Then install the latest pip version(8.1.2): `sudo python -m pip install pip --upgrade`
3, If you installed pip from pip, upgrade pip to 8.1.2 directly: `sudo pip install pip --upgrade`
